server {
    listen 80;

    location /health {
        default_type application/json;
        return 200 '{"status":"ok","module":"05-siem"}';
    }

    location / {
        default_type application/json;
        return 200 '{"module":"05-siem","note":"placeholder - reemplazad este contenedor por vuestro servicio real"}';
    }
}
